version: '3.8'

services:
  scanner_backend-api:
    container_name: main
    build: ./ 
    command: ./server
    env_file:
      - ./configs/.config.env 
    ports:
      - 3000:3000
    depends_on: 
      - db
    restart: always
    
  db:
    image: postgres:latest 
    env_file:
      - ./configs/.config.env
    environment:
      - PG-DATA=/var/lib/postgresql/data   
    ports:
      - 5436:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: