version: '1.0'

services:
  scanner_backend-api:
    container_name: main
    env_file:
      - ./configs/.config.env 
    build: 
      context: .
    command: ./wait-for-postgres.sh db ./server
    ports:
      - 3000:3000
      - 8080:8080
      - 9229:9229
    depends_on: 
      - postgres
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres:14 
    env_file:
      - ./configs/.config.env
    environment:
      -PG-DATA: /var/lib/postgresql/data   
      -POSTGRES-PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: