// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReplieRepo is an autogenerated mock type for the ReplieRepo type
type ReplieRepo struct {
	mock.Mock
}
