// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SavedRepo is an autogenerated mock type for the SavedRepo type
type SavedRepo struct {
	mock.Mock
}
