// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	model "github.com/VladPetriv/scanner_backend_api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SavedRepo is an autogenerated mock type for the SavedRepo type
type SavedRepo struct {
	mock.Mock
}

// CreateSavedMessage provides a mock function with given fields: savedMessage
func (_m *SavedRepo) CreateSavedMessage(savedMessage *model.Saved) (int, error) {
	ret := _m.Called(savedMessage)

	var r0 int
	if rf, ok := ret.Get(0).(func(*model.Saved) int); ok {
		r0 = rf(savedMessage)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Saved) error); ok {
		r1 = rf(savedMessage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSavedMessage provides a mock function with given fields: ID
func (_m *SavedRepo) DeleteSavedMessage(ID int) (int, error) {
	ret := _m.Called(ID)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSavedMessages provides a mock function with given fields: ID
func (_m *SavedRepo) GetSavedMessages(ID int) ([]model.Saved, error) {
	ret := _m.Called(ID)

	var r0 []model.Saved
	if rf, ok := ret.Get(0).(func(int) []model.Saved); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Saved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSavedRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewSavedRepo creates a new instance of SavedRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSavedRepo(t mockConstructorTestingTNewSavedRepo) *SavedRepo {
	mock := &SavedRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
