// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WebUserRepo is an autogenerated mock type for the WebUserRepo type
type WebUserRepo struct {
	mock.Mock
}
