// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReplieService is an autogenerated mock type for the ReplieService type
type ReplieService struct {
	mock.Mock
}
