// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SavedService is an autogenerated mock type for the SavedService type
type SavedService struct {
	mock.Mock
}
