// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	model "github.com/VladPetriv/scanner_backend_api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SavedService is an autogenerated mock type for the SavedService type
type SavedService struct {
	mock.Mock
}

// CreateSavedMessage provides a mock function with given fields: savedMessage
func (_m *SavedService) CreateSavedMessage(savedMessage *model.Saved) error {
	ret := _m.Called(savedMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Saved) error); ok {
		r0 = rf(savedMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSavedMessage provides a mock function with given fields: ID
func (_m *SavedService) DeleteSavedMessage(ID int) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSavedMessages provides a mock function with given fields: ID
func (_m *SavedService) GetSavedMessages(ID int) ([]model.Saved, error) {
	ret := _m.Called(ID)

	var r0 []model.Saved
	if rf, ok := ret.Get(0).(func(int) []model.Saved); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Saved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSavedService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSavedService creates a new instance of SavedService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSavedService(t mockConstructorTestingTNewSavedService) *SavedService {
	mock := &SavedService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
