// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/VladPetriv/scanner_backend_api/internal/model"

// WebUserService is an autogenerated mock type for the WebUserService type
type WebUserService struct {
	mock.Mock
}

// CreateWebUser provides a mock function with given fields: user
func (_m *WebUserService) CreateWebUser(user *model.WebUser) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.WebUser) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWebUserByEmail provides a mock function with given fields: email
func (_m *WebUserService) GetWebUserByEmail(email string) (*model.WebUser, error) {
	ret := _m.Called(email)

	var r0 *model.WebUser
	if rf, ok := ret.Get(0).(func(string) *model.WebUser); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WebUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
