// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WebUserService is an autogenerated mock type for the WebUserService type
type WebUserService struct {
	mock.Mock
}
