name: ci

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  go_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with: {go-version: 1.17}

      - uses: actions/checkout@v3

      - name: Go modules Cache 
        uses: actions/cache@v2
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run unit tests...
        run: go test -v ./...
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
